export const Store = {
  KNOWLEDGE_INCREASE: 'KNOWLEDGE_INCREASE',
  KNOWLEDGE_DECREASE: 'KNOWLEDGE_DECREASE',

  MENU_SELECT: 'MENU_SELECT',

  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  USER_LOGIN_PROCESSING: 'USER_LOGIN_PROCESSING',

  NOTIFY_COMPLETED: 'NOTIFY_COMPLETED',
  NOTIFY_LOGIN_SUCCESS: 'NOTIFY_LOGIN_SUCCESS',
  NOTIFY_LOGIN_FAIL: 'NOTIFY_LOGIN_FAIL'
}
export const Saga = {
  USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST'
}
