export const Store = {
  KNOWLEDGE_INCREASE: 'KNOWLEDGE_INCREASE',
  KNOWLEDGE_DECREASE: 'KNOWLEDGE_DECREASE',
  MENU_SELECT: 'MENU_SELECT',
  USER_LOGIN_SUCCEESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL'
}
export const Saga = {
  USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST'
}
